16:35:49:3  |SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:35:49:9  |SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:35:49:41 |SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:35:49:47 |SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:35:49:69 |FAILURE   |               |tbl_query      |database_*le_util.py|unable to execute query [select col1,col2,col3 from foofoo] in db [.//foobar.sqlite] [no such table: foofoo]
16:35:49:92 |SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:35:49:97 |SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:35:49:127|SUCCESS   |               |tbl_create     |database_util.py    |created table [foobar] in db [foobar.sqlite]
16:35:49:139|SUCCESS   |               |tbl_rows_insert|database_*le_util.py|inserted [1] into table [foobar] in db [foobar.sqlite]
16:35:49:163|INFO      |               |_parse*ut_file |excel_dat*se_util.py|setting runtime_path to [.]
